### ISSUE TITLE
Refine restrictions on `Tag` class

### ISSUE THREAD

**Issue by chia-yh** [AY2223S2-CS2103T-T12-4/tp#132]
- [x] restrict `Tag` length @chia-yh 
- [ ] restrict number of `Tag` instances @huanghao1998

**Comment by chia-yh** [comment]
@huanghao1998 any updates on this?

**Comment by huanghao1998** [comment]
> @huanghao1998 any updates on this?

Yes, could you help me to check if I implemented correctly. #172 
Thanks
