### ISSUE TITLE
[PE-D][Tester B] `find` with no args works, but filters all the person

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T12-4/tp#216]
## Before

![image.png](https://raw.githubusercontent.com/EvitanRelta/ped/master/files/9af7441e-959b-448f-95c5-0d4d6b46b21c.png)

## After

![image.png](https://raw.githubusercontent.com/EvitanRelta/ped/master/files/f05b071a-b541-423a-b80b-b21a932bf7af.png)

## It's stated in the UG, tho its kind of a weird behaviour

![image.png](https://raw.githubusercontent.com/EvitanRelta/ped/master/files/3d817119-26ca-4a68-accb-1ad107ea3abe.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: EvitanRelta/ped#2

**Comment by chia-yh** [comment]
**Won't fix / invalid** : _Works as documented in UG._
