### ISSUE TITLE
[PE-D][Tester A] Name allowing digits

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T12-4/tp#233]
![image.png](https://raw.githubusercontent.com/Dangabit/ped/main/files/66115961-e83c-4e85-bbeb-b7e304818156.png)

I haven't met someone with digits in their names yet, but perhaps restrict Name further to disallow them?

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: Dangabit/ped#4

**Comment by chia-yh** [comment]
Won't fix / invalid : Follows convention of contact management applications where there are no restrictions digits in the name.
